import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import Header from "../components/header/header.component";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  <Head>
    <title>Product Listing Page</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;
  return (
    <Header />
  );
};
export default Home;
