import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { NextPage } from "next";
import Header from "../components/header/header.component";
import CardGrid from "../components/card-grid/card-grid.component";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import { Card } from "../components/card-grid/card-grid.types";

export interface IHomeProps {
  products: Card[];
}
const PRODUCTS_QUERY = gql`
  query Query {
    getProducts {
      id
      name
      imageSrc
      imageAlt
      price
      brand
    }
  }
`;
const Home: NextPage<IHomeProps> = ({ products }) => {
  return (
    <div className="md:mx-72">
      <Head>
        <title>Product Listing Page</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="title"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <CardGrid cards={products} />
      </div>
    </div>
  );
};
export default Home;

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "http://localhost:3000/api/graphql",
    cache: new InMemoryCache({
      addTypename: false,
    }),
  });
  const { data } = await client.query({
    query: PRODUCTS_QUERY,
  });
  return {
    props: {
      products: data.getProducts,
    },
  };
}
